# Generated by Django 3.0.6 on 2020-05-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200528_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
